[package]
name = "chi2mc_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "chi2mc_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
numpy = "0.23"
rand = "0.8"
rand_chacha = "0.3"
